### ISSUE TITLE
MySQL connection timing out after a few hours

### ISSUE THREAD

**Issue by NathanRignall** [NathanRignall/WhizzPlayer#3]
The MySQL connection in the API times out after a few hours of being on despite the constant "grab" requests from the backend. 

"ECONNRESET" is the message that appears. In production docker compose the container restarts but could be an issue if the time lines up with a cue/instant play.

**Comment by NathanRignall** [comment]
The backend should have retry functionality in the grab requests to the api a few seconds after a failed attempt to avoid missing songs. This is not just for the MySQL timeout error but for all errors too.

**Comment by NathanRignall** [comment]
Added retry functionality and changed to use a MySQL pool in v1.0.1.

The MySQL is still timing out after 8 hours.

Retry functionality does appear to work.

**Comment by NathanRignall** [comment]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/usr/src/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:315:20)
    at Protocol._delegateError (/usr/src/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/usr/src/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/usr/src/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
